language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - ./gradlew jacocoTestReport coveralls

before_deploy:
  - zip -r open-inzido *
  - mkdir -p deploy
  - mv open-inzido.zip deploy/open-inzido.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_API_INZIDO_LOCATION
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ws2cool/open-inzido
      branch: master